#!/usr/bin/env bash
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
	stats timeout 30s
	user haproxy
	group haproxy
	daemon


defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
        timeout connect 5000
        timeout client  50000
        timeout server  50000
frontend frontend
    bind *:80
    bind *:443 ssl crt /etc/haproxy/certs/www.nyambu.tech.pem
    mode http
    default_backend backend
backend backend
    balance roundrobin
    server 438060-web-01 18.210.14.174:80 check
    server 438060-web-02 100.25.167.146:80 check
